name: Deploy

on:
  pull_request:
    branches:
      - main
env:
  ITCH_USERNAME: e-dong
  ITCH_GAME_ID: spacewar-dev
jobs:
  deploy:
    name: Upload to Itch
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        channel:
          - web
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: make web-pack
      - uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.BUTLER_API_KEY}}
          gameData: ./tmp/build/web.zip
          itchUsername: ${{env.ITCH_USERNAME}}
          itchGameId: ${{ env.ITCH_GAME_ID }}
          buildChannel: ${{ matrix.channel }}
          buildNumber: ${{ needs.version.outputs.version_hash }}
