name: Deploy PR

on:
  pull_request:
    branches:
      - main
env:
  ITCH_USERNAME: e-dong
  ITCH_GAME_ID: spacewar-dev
jobs:
  deploy:
    name: Upload to Itch
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        channel:
          - web
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: "3.11.x"
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: "x64"
      - run: make web-pack
      - name: set-env
        run: bash .github/workflows/env.sh
      - uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.BUTLER_API_KEY}}
          gameData: tmp/build/web
          itchUsername: ${{env.ITCH_USERNAME}}
          itchGameId: ${{ env.ITCH_GAME_ID }}
          buildChannel: ${{ matrix.channel }}
          buildNumber: $version
